#+title: [[https://user.guancha.cn/user/personal-homepage?uid=239938][悄然逝去的吹哨人：20年前她揭开了“艾滋血祸”]] 
#+author: [[https://user.guancha.cn/user/personal-homepage?uid=239938][疫苗与科学]]

陶医生按：

艾滋病目前还无法治愈，疫苗研发也困难重重。

医者仁心。王淑平发现了我国当年的采供血制度里存在艾滋病污染的恐怖漏洞，她一次又一次向上级反映情况。

她的工作没了，婚姻破裂了，幸福消失了，但同时救了成千上万人的命。

她是中国人民的英雄，遭受了不公平的待遇，希望以后会给她一个公道。


王淑平医生近照

2019年9月21日，20多年前艾滋血祸事件揭发人王淑平医生，在美国犹他州心脏病发作去世，享年59岁。

她生前是个普通的医生，研究流行病，30多岁时做了一件职责范围之内但需要勇气的事，然后为此付出了人生代价。

“吹哨”是件危险的事，因为会触动某些暗黑利益；吹哨者个人往往会因此付出代价。王淑平生前最后一次接受媒体采访时说：“我没有考虑自己的命运。这是医生职业操守的第一条。”

她去世前不久，以20多年前河南艾滋村和“卖血经济”为题材创作的一出舞台剧在英国伦敦上演，名为《地狱宫殿的国王》。编剧高雅竹是半个华裔，父亲曾任美国外交官，母亲是台湾人。她见过王淑平，对20多年前河南的“卖血经济”并不陌生。

王淑平1991年开始在区卫生局下属的血站工作。不久，她发现当时在河南盛极一时的“卖血经济”中一个可怕的安全漏洞――艾滋病病毒和肝炎病毒携带者卖血，血站的血液制品受了污染，然后又通过不同渠道传染给健康的献血者和更多无辜的健康民众。

血站本身成了一个公共卫生隐患。

更可怕的是，当时还存在很多民间私人血站――并没有任何卫生资质，一个会计、两个护士、几个针管、几瓶酒精，把牛棚改造一下，就成了人们趋之若鹜的“采血点”。这样的“黑血站”还像雨后春笋一样越冒越多，有人统计过，1993年，仅驻马店地区就有33个。

当时国内实行禁止血液制品进口的政策，以防止海外的各种病毒通过血液制品入境。但当时的技术在血液的采集和处理方面十分落后，没有任何预防污染、交叉感染的措施。

许多人卖血求生，但对这个过程中的病毒感染危险没有丝毫概念。无论是官办的还是民办的血站都没有肝炎和艾滋病毒排查机制。因此，丙肝病毒在各地的采血站畅通无阻。

王淑平写了疫情报告后，卫生部下令必须对献血卖血者做丙肝病毒检测，她则被直接上司调离血站。

她随即成立了一个临床检验中心，挂靠在卫生局，财务自理，主要工作是筛查血液样本。很快，她发现一个更恐怖的漏洞：一位艾滋病毒携带者曾在4个血站卖过血。写报告请求血站排查艾滋病毒携带者，被告知太费钱，事情又不了了之。

王淑平从收集到的400多份血液样本中发现超过10%有艾滋病毒。1995年冬，她坐下来开始写疫情报告。见地方卫生部门不理睬，次年又她把报告和检测数据上交卫生部。


1995年12月，王淑平向周口地区卫生局递交的报告

她知道这么做意味着给自己惹麻烦吗？

“我当时没这么想，我只想马上采取行动来解决问题。作为医生，我首先考虑的是病人和公众的利益，不是我自己。我有机会修改报告，但事情越来越紧迫，如果不这么做会有严重后果。”

“我遇到了巨大的麻烦，涉及到权力金钱和无钱无势者的冲突。我决定为感染丙型肝炎病毒和艾滋病毒的无辜的人站出来。”王淑平去世前一个月接受伦敦Hampstead剧场官网采访，她这么回答。

最后的结果是她被开除公职。她当时的丈夫在卫生部工作，因为妻子“吹哨”揭露“血祸”，在机关也受到排挤，最后两人离婚。王淑平告别子女只身前往美国，从此再也没有回过中国。

但她的吹哨达到了目的。1996年，国内各地所有的血站都关门整顿。血站恢复工作后，增加了抽血前必须查验艾滋病毒（HIV）这一项。王淑平很开心，因为很多人将因此免于无辜感染病毒。

去世前不久的一天，王淑平接受《女性时光》节目采访，回忆当时的情形：有一个地方卫生官员在一次公共卫生工作会议上公开抱怨，说哪个家伙那么大胆，居然把这事报告到中央。我站起来说，报告是我写的，我是女人。

2001年，王淑平只身一人移居美国，英语名叫 Sunshine，意思是阳光。就在那一年，华中地区面临艾滋病危机获得承认，至少50万人在血站卖血后感染艾滋病毒，其中河南是艾滋病毒疫情最严重的一个省。政府后来开了一家专科医院，专治与艾滋病相关的病患。

很多年以后，王淑平和美国人结婚，到盐湖城定居。她在犹他州大学当研究员。但往事并不如烟。

2019年，王淑平在河南的亲属和以前的同事被通知，要设法让她出面阻止根据她的经历获得灵感创作的舞台剧公演，但她没有答应。《地狱宫殿的国王》9月5日如期在伦敦公演。

9月21日，王淑平在盐湖城登山途中猝死，据信她死于心脏病。

王淑平承认，说实话付出了代价：工作没了，婚姻破裂了，幸福消失了，但同时救了成千上万人的命。

她的朋友高大伟得知王淑平去世的消息后发推特致哀：“她是个意志坚定、无比乐观、极富爱心的女性。”“她是我的英雄，我的朋友。”

免责声明
以上内容为用户在观察者网风闻社区上传并发布，仅代表发帖用户观点。 

